# makefile for Borland Turbo C 2.0/Turbo C++ 1.01
#
# make -fMakefile.tc

CP=copy
RM=del

CC=tcc
CFLAGS=-ms -O
LIBS=
LDFLAGS=

HDRS=dumpmem.h helper.h


all: bpbdpb.exe dskrd.exe

clean:
	-$(RM) bpbdpb.exe
	-$(RM) dskrd.exe
	-$(RM) *.obj


bpbdpb.exe: bpbdpb.c $(HDRS)
	$(CC) $(CFLAGS) -ebpbdpb.exe bpbdpb.c $(LIBS) $(LDFLAGS)

dskrd.exe: dskrd.c dskrd_h.obj $(HDRS)
	$(CC) $(CFLAGS) -edskrd.exe  dskrd.c dskrd_h.obj $(LIBS) $(LDFLAGS)

dskrd_h.obj: dskrd_h.asm
	nasm -f obj -o dskrd_h.obj dskrd_h.asm


